/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

// Classpath that holds the Spokk K2 compiler plugin together with the Power-assert plugin it reuses.
// These jars are loaded by the Kotlin compiler via `-Xplugin`.
val spokkCompilerPlugin: Configuration by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
}

dependencies {
    // The Spokk runtime exposes JUnit 5 `DynamicTest`s from its data-driven `where(...)` API, so
    // `junit-jupiter-api` is part of the public API. `kotlinx-coroutines-core` powers the
    // `runBlocking` call that drives `suspend` data-driven bodies.
    api(libs.junit.jupiter.api)
    implementation(libs.kotlinx.coroutines.core)

    // Use the Kotlin Test integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Required by JUnit to discover and invoke `suspend` test functions.
    testImplementation("org.jetbrains.kotlin:kotlin-reflect")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // The Spokk compiler plugin jar and the Power-assert compiler plugin it delegates to.
    spokkCompilerPlugin(project(":compiler-plugin")) { isTransitive = false }
    spokkCompilerPlugin(libs.kotlin.power.assert.compiler.plugin.embeddable) { isTransitive = false }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType<KotlinCompile>().configureEach {
    inputs.files(spokkCompilerPlugin)
        .withPropertyName("spokkCompilerPlugin")
        .withNormalizer(ClasspathNormalizer::class)

    compilerOptions {
        // Load the Spokk K2 compiler plugin (+ Power-assert) into the compiler.
        freeCompilerArgs.addAll(
            spokkCompilerPlugin.elements.map { locations ->
                locations.map { "-Xplugin=${it.asFile.absolutePath}" }
            },
        )
        // Enable the experimental collection-literals syntax: `[1, 2, 3]`.
        freeCompilerArgs.add("-Xcollection-literals")
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()

    // Surface the power-assert diagrams in the build output.
    testLogging {
        events("passed", "failed", "skipped")
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        showStandardStreams = true
    }
}
